#!/bin/bash

# This script is used to build, test, and install the project
echo "Running ./run"






#log environment variables $LOG_PATH and $LOG_LEVEL
loglevel="${LOG_LEVEL:-2}"
logdirectorypath="${LOG_FILE:-log.txt}"
ghtoken="${GITHUB_TOKEN:-faketokengithub}"
logfullpath= "$(logdirectorypath)/log.txt"

echo "LOG_FILE: $logdirectorypath"
echo "LOG FULL PATH: $logfullpath"
echo "LOG_LEVEL: $loglevel"
echo "Github Token: $ghtoken"



case "$1" in
    "build")
        #getting rid of old build
        echo "[BUILD] - Removing old build"
        rm -rf CLIParse
        rm -rf cache
        rm -rf log.txt
        rm -rf $logfullpath
        echo "[BUILD] - Old build removed"

        #make cache folders
        echo "Making cache folders"
        mkdir -p cache
        touch cache/pip.txt
        touch cache/build.txt
        touch cache/log.txt
        touch $logdirectorypath
        touch $logfullpath
        

        # build function code here
        echo "[BUILD] - Building C# CLI Parser"
        #check if loglevel is greater than 0
        if [ $loglevel -gt 0 ] 
        then
        echo "[BUILD|Priority: 1 (info)] - Building C# CLI Parser" | tee -a $logfullpath cache/build.txt
        fi

        dotnet publish CLIParseProj -r linux-x64 -p:PublishSingleFile=true --self-contained true | tee -a $logfullpath cache/build.txt
        cp CLIParseProj/bin/Debug/net6.0/linux-x64/publish/CLIParse .
        echo "[BUILD] - C# CLI Parser built"

        

        echo "[BUILD] - Build complete"
        if [ $loglevel -gt 0 ] 
        then
        echo "[BUILD|Priority: 1 (info)] - Build complete" | tee -a $logfullpath cache/build.txt
        fi
        ;;
    "test")
        # test function code here
        echo "Running tests"
        if [ $loglevel -gt 1 ] 
        then
        echo "BUILD|Priority: 2 (debug) - Running tests" | tee -a $logfullpath cache/build.txt
        fi
        ;;
    "clean")
        #getting rid of old build
        echo "[BUILD] - Removing old build"
        rm -rf CLIParse
        rm -rf cache
        rm -rf log.txt
        rm -rf npm.json
        rm -rf git.json
        rm -rf $logfullpath

        echo "[BUILD] - Old build removed"

        ;;
    "install")
        #make cache folders
        echo "Making cache folders"
        mkdir -p cache
        touch cache/pip.txt
        touch cache/build.txt
        touch cache/log.txt

        # install function code here
        echo "Installing Dependencies"
        if [ $loglevel -gt 0 ] 
        then
        echo "[BUILD|Priority: 1 (info)] - Installing Dependencies" | tee -a $logfullpath cache/build.txt
        fi

        echo "Installing Python Dependencies with pip"
        if [ $loglevel -gt 1 ] 
        then
        echo "[BUILD|Priority: 2 (debug)] - Installing Python Dependencies with pip" | tee -a $logfullpath cache/build.txt
        fi
        
        pip install -r requirements.txt > cache/pip.txt
        echo "Python Dependencies installed"
        if [ $loglevel -gt 1 ] 
        then
        echo "[BUILD|Priority: 2 (debug)] - Python Dependencies installed" | tee -a $logfullpath cache/build.txt
        fi

        #call logger
        ./CLIParse install $logdirectorypath $loglevel 

        echo "Dependencies installed"
        if [ $loglevel -gt 0 ] 
        then
        echo "[BUILD|Priority: 1 (info)] - Dependencies installed" | tee -a $logfullpath cache/build.txt
        fi
        ;;
    *)
        # code for running parse.exe with URL argument
        echo "Running parse.exe with FILE URI: $1"
        if [ $loglevel -gt 0 ] 
        then
        ./CLIParse $1 $logdirectorypath $loglevel
        fi
        ;;


esac
